### ISSUE TITLE
Unity Version

### ISSUE THREAD

**Issue by cyrusamirabadi** [GamEditor/Ballz-Brick-Breaker-Unity#1]
Hello there, 

Hope you are safe and sound. 

I was wondering if you can tell me which Unity version is the best one for this source code? I tried 2018.3.14f1 and I've got some errors.

Thanks, 
Cyrus

**Comment by GamEditor** [comment]
hello. sorry for this much late. I didn't saw issues. I built this game with unity 2017, but errors are not important and they are not from game's logic. they are came from google play api and other packages i used. i will make another commit after i answering you. so if you check this repo after almost 2 hours later, all errors gone.
hope you safe too.

**Comment by GamEditor** [comment]
i upgraded project to unity 2021.1
